# Generate face-identities demo seed SQL
# Run: python scripts/generate-face-seed.py > scripts/seed-face-identities-demo.sql

identities = [
    ("Viktor Petrov (DEMO-APT-01)", ["apt","threat-actor","demo-apt-01","ransomware","leader","russian"], "Leader of DEMO-APT-01. Responsible for MetaCorp, JPMorgan Demo, and Microsoft Demo breaches. Linked to CVE-2026-99001 and CVE-2026-99991. Observed using Raccoon and custom malware.", 97, True, None),
    ("Elena Volkov (DEMO-APT-01)", ["apt","threat-actor","demo-apt-01","malware-dev","coder","russian"], "Malware developer for DEMO-APT-01. Developed DEMO-WEBSHELL-01 and DEMO-LATERAL-01. Linked to MetaCorp and JPMorgan Demo breaches.", 91, True, None),
    ("Chen Wei (DEMO-APT-01)", ["apt","threat-actor","demo-apt-01","finance","analyst","chinese"], "Financial analyst for DEMO-APT-01. Specializes in targeting financial institutions including JPMorgan Demo Bank and PayPal Demo.", 89, True, None),
    ("Sergei Ivanov (NEXUS-THREAT)", ["apt","nexus-threat","cloud-hacker","leader","gcp","aws","russian"], "Leader of NEXUS-THREAT group. Specializes in cloud environment attacks targeting GCP, AWS, and Azure. Responsible for Google Demo and Amazon Demo breaches via shared OAuth trust exploitation.", 96, True, None),
    ("Maria Sokolova (NEXUS-THREAT)", ["apt","nexus-threat","stealer-dev","cloud-specialist","russian"], "Stealer developer for NEXUS-THREAT. Developed NEXUS-STEALER-01 (google_stealer.py) and NEXUS-STEALER-02 (aws_keylogger.exe). Both beacon to 198.51.100.75.", 93, True, None),
    ("Alexei Kozlov (NEXUS-THREAT)", ["apt","nexus-threat","exploit-dev","cve-researcher","russian"], "CVE researcher and exploit developer for NEXUS-THREAT. Linked to CVE-2026-99991 (Google Workspace SSO bypass) and CVE-2026-99994 (AWS S3 misconfiguration).", 88, True, None),
    ("Jin Park (PHANTOM-SHADOW)", ["apt","phantom-shadow","streaming-attacks","leader","south-korean"], "Leader of PHANTOM-SHADOW group. Specializes in streaming platforms and entertainment sector attacks. Linked to Netflix Demo and Spotify Demo breaches.", 90, True, None),
    ("Yuki Tanaka (PHANTOM-SHADOW)", ["apt","phantom-shadow","credential-stuffing","stealer","japanese"], "Operator for PHANTOM-SHADOW. Uses credential stuffing and stealer malware against streaming platforms. Developed PHANTOM-STEALER-01.", 85, True, None),
    ("Mohammed Al-Hassan (SILENT-RIFT)", ["apt","silent-rift","social-media","scraping","leader","iranian"], "Leader of SILENT-RIFT. Specializes in social media and professional network scraping. Responsible for LinkedIn Demo breach (900M profiles).", 92, True, None),
    ("Sara Mansouri (SILENT-RIFT)", ["apt","silent-rift","data-analyst","scraping","automation","iranian"], "Data analyst for SILENT-RIFT. Developed SILENT-RIFT-SCRAPER-01 for large-scale data extraction from professional networks.", 86, True, None),
    ("Min-Jun Lee (CYBER-SHADOW)", ["apt","cyber-shadow","fintech","gaming","leader","north-korean"], "Leader of CYBER-SHADOW group. Targets gaming and fintech sectors. Responsible for Steam Demo, PayPal Demo, and Uber Demo breaches.", 94, True, None),
    ("Soo-Yeon Kim (CYBER-SHADOW)", ["apt","cyber-shadow","payment-systems","crypto","north-korean"], "Financial operator for CYBER-SHADOW. Specializes in payment system compromise and cryptocurrency theft. Linked to PayPal Demo breach.", 88, True, None),
    ("Ali Tehrani (DEMO-APT-02)", ["apt","demo-apt-02","financial","banking","leader","iranian"], "Leader of DEMO-APT-02. Advanced persistent threat focused on financial institutions. Targets JPMorgan Demo Bank using spear-phishing and supply chain attacks.", 95, True, None),
    ("Dmitri Volkov (LockBit Affiliate)", ["ransomware","lockbit","affiliate","raas","russian"], "LockBit ransomware affiliate. Responsible for Microsoft Demo breach. Exploited CVE-2026-99993 (Azure AD privilege escalation) for initial access.", 93, True, None),
    ("Natasha Ivanova (ALPHV/BlackCat)", ["ransomware","alphv","blackcat","negotiator","russian"], "ALPHV/BlackCat ransomware operator. Responsible for JPMorgan Demo Bank breach. Selling internal network access on darkweb markets. $75K starting price.", 91, True, None),
    ("Carlos Mendez (Darkweb Vendor)", ["darkweb","vendor","data-sales","breach","mexican"], "Darkweb marketplace vendor specializing in database dumps. Selling MetaCorp, TikTok, and Apple Demo databases. Verified seller on versus_market and torrez_market.", 88, True, None),
    ("Omar Shaikh (Darkweb Vendor)", ["darkweb","vendor","access-sales","network-access","pakistani"], "Darkweb vendor specializing in network access sales. Selling JPMorgan Demo Bank internal access and Microsoft Demo Azure tenant access.", 90, True, None),
    ("Andrei Popov (Raccoon Developer)", ["malware-dev","stealer","raccoon","developer","ukrainian"], "Developer of Raccoon stealer malware. Raccoon used to harvest credentials from MetaCorp, Google Demo, Amazon Demo, and JPMorgan Demo employees. Captured 234+ credentials per host.", 92, True, None),
    ("Katarina Novak (RedLine Developer)", ["malware-dev","stealer","redline","coder","polish"], "Developer of RedLine stealer. RedLine used against Google Demo and MetaCorp targets. Captures browser cookies, autofill data, and credentials.", 89, True, None),
    ("Viktor Koval (Lumma Developer)", ["malware-dev","stealer","lumma","infostealer","ukrainian"], "Developer of Lumma stealer (infostealer). Lumma used against Google Demo, Microsoft Demo, and TikTok Demo. Captures 312+ credentials per host.", 87, True, None),
    ("@DarkOperatorX (Telegram Admin)", ["telegram","channel-admin","darkleaks","data-dumps","russian"], "Telegram channel admin for DarkLeaks Underground (4500 members). Daily dumps of credential databases including MetaCorp 500K employee database.", 90, True, "@DarkOperatorX"),
    ("@ShadowBroker (Telegram Admin)", ["telegram","channel-admin","stealer-logs","combo-list","russian"], "Telegram channel admin for stealer logs channel (8000+ members). Distributes Raccoon + Lumma combo with 25K+ credentials. Compiled 2M line mega combo.", 93, True, "@ShadowBroker"),
    ("Hassan Raza (Exploit Developer)", ["exploit-dev","zero-day","cve-research","researcher","pakistani"], "Zero-day exploit developer. Developed working exploits for CVE-2026-99001, CVE-2026-99992, and CVE-2026-99999. Sells to multiple threat actor groups.", 91, True, None),
    ("Maxim Petrov (C2 Admin)", ["c2-admin","infrastructure","botnet","server-admin","russian"], "C2 infrastructure administrator. Manages C2 servers at IPs 198.51.100.50 (MetaCorp C2), 203.0.113.200 (JPMorgan C2), 198.51.100.75 (NEXUS-THREAT C2).", 94, True, None),
    ("Arseni Volkov (Phishing Kit Dev)", ["phishing","kit-dev","credential-harvest","social-engineering","russian"], "Phishing kit developer. Created phishing pages impersonating MetaCorp, JPMorgan Demo, Google Demo, Microsoft Demo, and Amazon Demo. Kits hosted on 198.51.100.50, 203.0.113.200.", 86, True, None),
    ("Wei Chen (Crypto Mixer Operator)", ["crypto","mixer","money-laundering","financial-crime","chinese"], "Cryptocurrency mixer operator. Helps threat actors launder proceeds from ransomware attacks, credential sales, and data breaches. Linked to LockBit and ALPHV payments.", 89, True, None),
    ("Liang Zhang (Supply Chain Attack)", ["supply-chain","apt","third-party","compromise","chinese"], "Supply chain attack specialist. Responsible for compromises via third-party vendors and open-source package poisoning. NPM and PyPI repository tampering linked to OLGA SERGEEVA.", 92, True, None),
    ("Nina Petrova (Social Engineering)", ["social-engineering","deepfake","impersonation","ai-tools","ukrainian"], "Social engineering and deepfake specialist. Uses AI-generated voices and deepfake videos for impersonation attacks against executives at MetaCorp and JPMorgan Demo.", 84, True, None),
    ("Priya Sharma (Insider Threat)", ["insider-threat","data-theft","tech-company","disgruntled","indian"], "Suspected insider threat at tech company. Disgruntled employee allegedly providing internal access to threat actors. Under investigation.", 87, True, None),
    ("James Okafor (BEC Actor)", ["bec","fraud","impersonation","financial-crime","nigerian"], "Business Email Compromise (BEC) actor. Conducts CEO fraud and invoice scams targeting financial institutions. Linked to JPMorgan Demo and PayPal Demo compromise.", 85, True, None),
    ("Robert Chen (MetaCorp CEO)", ["victim","metacorp","ceo","high-profile","breach","american"], "MetaCorp CEO. High-profile victim of MetaCorp breach. 2.9B records exfiltrated. Executive credentials found in stealer logs.", 45, False, None),
    ("Sarah Mitchell (MetaCorp CTO)", ["victim","metacorp","cto","technical","breach","american"], "MetaCorp CTO. Technical leadership role compromised in MetaCorp breach. Linked to CVE-2026-99001 exploitation chain.", 42, False, None),
    ("Michael Brown (MetaCorp IT Admin)", ["victim","metacorp","it-admin","privileged","stealer-log","american"], "MetaCorp IT Administrator. High-privilege account found in Raccoon stealer logs from meta-host-005. Domain admin access confirmed.", 78, True, None),
    ("David Kim (MetaCorp DevOps)", ["victim","metacorp","devops","cloud","stealer-log","american"], "MetaCorp DevOps Engineer. Cloud infrastructure access found in stealer logs. AWS and Azure credentials potentially compromised.", 75, True, None),
    ("Jennifer Wu (MetaCorp HR Director)", ["victim","metacorp","hr","employee-data","breach","american"], "MetaCorp HR Director. Employee records and sensitive HR data potentially exposed in breach. Linked to MetaCorp 500K employee database dump.", 55, False, None),
    ("Victoria Sterling (JPMorgan Demo CEO)", ["victim","jpmorgan-demo","ceo","high-profile","financial","american"], "JPMorgan Demo CEO. High-profile financial sector victim. Internal network access confirmed compromised. ALPHV/BlackCat auction started at $75K.", 60, False, None),
    ("Alexander Morgan (JPMorgan Trading)", ["victim","jpmorgan-demo","trading","bloomberg","stealer-log","british"], "JPMorgan Demo Head of Trading. Bloomberg Terminal credentials found in Vidar stealer logs (jpm-host-002). Trading system access confirmed compromised.", 85, True, None),
    ("Marcus Thompson (JPMorgan IT Director)", ["victim","jpmorgan-demo","it-director","domain-admin","critical","american"], "JPMorgan Demo IT Director. Domain admin account found in Raccoon stealer logs. Full internal network compromise confirmed.", 92, True, None),
    ("Emily Chen (JPMorgan Risk Analyst)", ["victim","jpmorgan-demo","risk-analyst","clearance-l3","american"], "JPMorgan Demo Risk Analyst. Level 3 security clearance. Risk dashboard access found in Lumma stealer logs.", 65, False, None),
    ("Richard Hayes (JPMorgan Senior Trader)", ["victim","jpmorgan-demo","senior-trader","derivatives","stealer-log","american"], "JPMorgan Demo Senior Trader (Derivatives desk). Bloomberg and internal trading credentials captured by Vidar stealer. Trading system compromise.", 80, True, None),
    ("Jonathan Lee (Google Demo Cloud Architect)", ["victim","google-demo","cloud-architect","gcp","stealer-log","american"], "Google Demo Cloud Architect. GCP service account keys found in stealer logs from google-host-001. 12 projects with Owner permissions compromised. NEXUS-THREAT linked.", 88, True, None),
    ("Lisa Park (Google Demo Security Engineer)", ["victim","google-demo","security-engineer","service-account","american"], "Google Demo Security Engineer. Service account credentials found in GitHub public repo (gh-google-001). GCP BigQuery and GCS access compromised. NEXUS-STEALER-01 linked.", 86, True, None),
    ("Thomas Anderson (Google Demo Data Engineer)", ["victim","google-demo","data-engineer","bigquery","stealer-log","german"], "Google Demo Data Engineer. BigQuery access credentials found in Lumma stealer logs (google-host-003). Analytics data potentially exfiltrated.", 72, True, None),
    ("Daniel Garcia (Microsoft Demo Azure Admin)", ["victim","microsoft-demo","azure-admin","global-admin","critical","american"], "Microsoft Demo Azure AD Global Admin. Global admin credentials found in Raccoon stealer logs (ms-host-001). Full Azure tenant compromise. LockBit affiliate selling access for $20K.", 96, True, None),
    ("Rachel Torres (Microsoft Demo DevOps Lead)", ["victim","microsoft-demo","devops","azure-devops","stealer-log","american"], "Microsoft Demo DevOps Lead. Azure DevOps credentials found in RedLine stealer logs (ms-host-002). Project Collection Admin access. Source code potentially exposed.", 81, True, None),
    ("Kevin Walsh (Microsoft Demo SQL Admin)", ["victim","microsoft-demo","sql-admin","db-owner","stealer-log","american"], "Microsoft Demo SQL Administrator. Azure SQL db_owner credentials found in Lumma stealer logs (ms-host-003). Database access confirmed compromised.", 78, True, None),
    ("Amanda Foster (Amazon Demo DevOps)", ["victim","amazon-demo","devops","aws","stealer-log","american"], "Amazon Demo DevOps Engineer. AWS credentials found in Raccoon stealer logs (aws-host-001). PowerUser role with access to multiple regions.", 85, True, None),
    ("Christopher Lee (Amazon Demo Root)", ["victim","amazon-demo","root-account","admin","critical","american"], "Amazon Demo Root Account Holder. AWS root credentials found in paste site (paste-aws-001) and Stealc stealer logs (aws-host-004). Full AWS account compromise with unrestricted access.", 98, True, None),
    ("Jessica Martinez (Amazon Demo Seller)", ["victim","amazon-demo","seller","seller-central","american"], "Amazon Demo Premium Seller. Seller Central credentials found in RedLine stealer logs (aws-host-002). Sales data and payment information potentially accessed.", 68, False, None),
    ("Brandon Scott (Apple Demo Enterprise Admin)", ["victim","apple-demo","enterprise-admin","mdm","stealer-log","american"], "Apple Demo Enterprise Admin. MDM credentials found in stealer logs. 500 devices under management potentially compromised. PHANTOM-SHADOW linked to iCloud breach.", 83, True, None),
    ("Sophia Turner (Netflix Demo Content Exec)", ["victim","netflix-demo","content-exec","premium-account","american"], "Netflix Demo Content Executive. Premium account credentials found in stealer logs. Content production data potentially exposed. PHANTOM-SHADOW attributed.", 60, False, None),
    ("Lucas Fernandez (Spotify Demo Artist)", ["victim","spotify-demo","artist","1.2m-followers","stealer-log","spanish"], "Spotify Demo Artist with 1.2M followers. Spotify for Artists credentials found in stealer logs. Payout data ($45K) and listener analytics potentially exposed.", 72, True, None),
    ("Nina Patel (PayPal Demo Merchant)", ["victim","paypal-demo","merchant","balance-125k","stealer-log","indian"], "PayPal Demo Merchant with $125K balance. Merchant credentials found in Stealc stealer logs. Financial access confirmed compromised. CYBER-SHADOW selling access on darkweb.", 88, True, None),
    ("Michael Johnson (Salesforce Demo Admin)", ["victim","salesforce-demo","admin","system-admin","stealer-log","american"], "Salesforce Demo System Admin. Admin credentials found in stealer logs. 200K CRM org data potentially exposed. DEMO-RANSOM-01 linked.", 84, True, None),
    ("Sarah Connor (Uber Demo Engineering Manager)", ["victim","uber-demo","engineering-manager","ATG-team","stealer-log","american"], "Uber Demo Engineering Manager (ATG team). Credentials found in stealer logs. Self-driving technology data potentially at risk. DEMO-RANSOM-02 linked.", 79, True, None),
    ("Andrew Wilson (LinkedIn Demo Recruiter)", ["victim","linkedin-demo","recruiter","premium","stealer-log","american"], "LinkedIn Demo Premium Recruiter. 900M profile data scraped by SILENT-RIFT group. 50 inmail credits and candidate data exposed.", 65, False, None),
    ("Erik Johansson (Steam Demo VIP Gamer)", ["victim","steam-demo","gamer-vip","inventory-2500","stealer-log","swedish"], "Steam Demo VIP Gamer with $2,500 inventory value. Steam credentials found in Aurora stealer logs (steam-host-001). CYBER-SHADOW selling gaming accounts on darkweb at $50/account.", 70, True, None),
    ("Maria Santos (TikTok Demo Creator)", ["victim","tiktok-demo","creator","5m-followers","stealer-log","brazilian"], "TikTok Demo Creator with 5M followers. Creator account credentials found in Raccoon stealer logs (tiktok-host-001). Payout and analytics data potentially accessed.", 74, True, None),
    ("James Turner (TikTok Demo Brand Partner)", ["victim","tiktok-demo","brand-partner","verified","stealer-log","british"], "TikTok Demo Verified Brand Partner. Brand advertising credentials found in RedLine stealer logs (tiktok-host-002). Ad spend and campaign data exposed.", 71, True, None),
    ("Ivan Petrov (Ransomware Developer)", ["ransomware-dev","builder","double-extortion","russian"], "Ransomware developer. Created DEMO-RANSOM-01 (DeadboltDemo) and DEMO-RANSOM-02 (CryptVault) families. Uses double-extortion model with data leak threats.", 94, True, None),
    ("Yuri Sokolov (Botnet Operator)", ["botnet","operator","drdos","infrastructure","russian"], "Botnet operator. Manages large-scale botnet infrastructure used for DDoS attacks and spam campaigns. Linked to ransomware distribution.", 90, True, None),
    ("Gabor Nagy (ATM Malware Developer)", ["atm-malware","jackpotting","financial-crime","hungarian"], "ATM malware (jackpotting) developer. Targets financial institutions including JPMorgan Demo Bank. Playscale ATM malware linked to him.", 88, True, None),
    ("Fedor Ivanov (Banking Trojan Dev)", ["banking-trojan","emotet","loader","malware-dev","russian"], "Banking trojan and loader developer. Created malware used against JPMorgan Demo Bank and PayPal Demo. Emotet-style distribution chain.", 91, True, None),
    ("Zhang Wei (Cryptominer Operator)", ["cryptominer","crypto-jacking","cloud-exploitation","chinese"], "Cryptominer operator. Exploits cloud environments (AWS, GCP, Azure) for cryptocurrency mining. Linked to NEXUS-THREAT group.", 82, True, None),
    ("Rafael Costa (POS Malware Developer)", ["pos-malware","memory-scraping","retail-fraud","brazilian"], "Point-of-sale malware developer. Creates memory-scraping malware for retail environments. Linked to payment card theft from streaming service subscribers.", 85, True, None),
    ("Gabriel Moreau (Government Spyware Dev)", ["spyware","government","surveillance","mercenary","french"], "Government spyware developer. Creates surveillance tools sold to nation-state actors. Linked to multiple APT groups including DEMO-APT-01.", 93, True, None),
    ("Dmitri Volkov (DDoS-for-Hire)", ["ddos","booter","stressor","hired-gunner","russian"], "DDoS-for-hire (booter/stresser) service operator. Offers paid DDoS attacks targeting streaming platforms and financial institutions. Operates stresser platform.", 79, True, None),
    ("Alexei Petrov (Carding Forum Admin)", ["carding","forum-admin","financial-crime","underground","russian"], "Carding forum administrator. Manages underground forum for selling stolen payment cards and credentials. Linked to JPMorgan Demo and PayPal Demo card data.", 90, True, None),
    ("Carlos Reyes (SIM Swap Specialist)", ["sim-swap","cryptocurrency-theft","telecom-fraud","colombian"], "SIM swap fraud specialist. Conducts telecom fraud to hijack phone numbers for cryptocurrency theft. Targets executives at financial institutions.", 87, True, None),
    ("Oleg Volkov (MaaS Operator)", ["maas","fake-id","identity-fraud","service-operator","russian"], "Malware-as-a-Service (MaaS) operator. Provides stealer malware (Raccoon, Lumma, RedLine) as subscription service to affiliates. Manages C2 infrastructure.", 88, True, None),
    ("Anna Kowalski (MetaCorp VP Engineering)", ["victim","metacorp","vp-engineering","high-privilege","polish"], "MetaCorp VP of Engineering. High-privilege account potentially compromised in MetaCorp breach. Engineering team leadership access.", 55, False, None),
    ("Thomas Wright (MetaCorp Security Analyst)", ["victim","metacorp","security-analyst","stealer-log","australian"], "MetaCorp Security Analyst. Security tooling credentials found in Raccoon stealer logs. Could enable lateral movement within security infrastructure.", 73, True, None),
    ("Sven Eriksson (Google Demo SRE)", ["victim","google-demo","sre","cloud-platform","stealer-log","swedish"], "Google Demo Site Reliability Engineer. Cloud infrastructure access found in stealer logs. NEXUS-THREAT targeting cloud platform engineers.", 80, True, None),
    ("Fatima Al-Rashid (Microsoft Demo Identity)", ["victim","microsoft-demo","identity-specialist","azure-ad","saudi"], "Microsoft Demo Identity Specialist. Azure AD identity management credentials found in Lumma stealer logs. Could enable identity-based attacks.", 83, True, None),
    ("Yuki Yamamoto (Amazon Demo Lambda Dev)", ["victim","amazon-demo","lambda-developer","serverless","japanese"], "Amazon Demo Lambda Developer. Serverless function execution access potentially compromised. NEXUS-THREAT targeting AWS Lambda environments.", 69, False, None),
    ("Diana Collins (JPMorgan Compliance)", ["victim","jpmorgan-demo","compliance","regulatory","british"], "JPMorgan Demo Compliance Officer. Regulatory and audit system access potentially compromised. ALPHV/BlackCat targeting compliance data.", 58, False, None),
    ("Kenji Watanabe (Netflix Demo Infra Eng)", ["victim","netflix-demo","infra-engineer","cdn","stealer-log","japanese"], "Netflix Demo Infrastructure Engineer. CDN and content delivery infrastructure access found in stealer logs. PHANTOM-SHADOW targeting streaming infrastructure.", 77, True, None),
    ("Omar Hassan (PayPal Demo API Dev)", ["victim","paypal-demo","api-developer","merchant-integration","egyptian"], "PayPal Demo API Developer. Merchant integration API credentials found in Stealc stealer logs. CVE-2026-99999 (API SQL injection) exploited against his systems.", 74, True, None),
    ("Maria Gonzalez (Spotify Demo Label Manager)", ["victim","spotify-demo","label-manager","music-industry","spanish"], "Spotify Demo Label Manager. Music industry partner access potentially compromised. PHANTOM-SHADOW targeting entertainment sector.", 61, False, None),
    ("Ryan Hughes (Salesforce Demo Integration Dev)", ["victim","salesforce-demo","integration-dev","connected-app","irish"], "Salesforce Demo Integration Developer. Connected app OAuth credentials found in stealer logs. CRM data for 200K organizations potentially accessible.", 75, True, None),
    ("MarketAdmin (Darkweb - Versus Market)", ["darkweb","marketplace-admin","versus","moderator","unknown"], "Versus darkweb marketplace administrator. Manages vendor verification, escrow, and dispute resolution for stolen data and access sales. Multiple demo company data listed.", 91, True, None),
    ("DarkVendor-01 (Darkweb Premium Seller)", ["darkweb","vendor","premium-seller","verified","russian"], "Premium darkweb vendor. Specializes in MetaCorp and TikTok Demo database sales. Verified seller with 500+ transactions. Selling 2.9B+ MetaCorp records and 1.2B TikTok records.", 90, True, None),
    ("DarkVendor-02 (Darkweb - AlphBay)", ["darkweb","vendor","financial-access","premium","unknown"], "AlphBay darkweb marketplace vendor specializing in financial sector access. Selling JPMorgan Demo Bank and Microsoft Demo Azure access. $20K-$75K range.", 92, True, None),
    ("Roman Volkov (Exploit Kit Developer)", ["exploit-kit","kit-dev","web-exploit","angler","russian"], "Exploit kit developer. Created web exploitation kits used in phishing campaigns against MetaCorp, Google Demo, and Amazon Demo employees. CVE-2026-99001 toolkit included.", 89, True, None),
    ("Elena Petrova (Ransomware Negotiator)", ["ransomware","negotiator","victim-interaction","double-extortion","russian"], "Ransomware group negotiator. Handles victim communication for DEMO-RANSOM-01 and LockBit affiliates. Negotiates ransom payments ranging from $500K to $5M.", 87, True, None),
    ("Sanjay Gupta (Mobile Trojan Developer)", ["mobile-trojan","banking-trojan","android","malware-dev","indian"], "Mobile banking trojan developer. Creates Android malware targeting banking apps including JPMorgan Demo mobile and PayPal Demo. Distributed via fake app stores.", 85, True, None),
    ("Max Kramer (Ex-Penetration Tester)", ["red-team","ex-pentester","turned-dark","social-engineering","german"], "Former penetration tester turned threat actor. Uses red team techniques for social engineering and network intrusion. Linked to JPMorgan Demo Bank compromise via phishing.", 86, True, None),
    ("ShadowAdmin (Dark Web Forum Mod)", ["forum","moderator","underground","reputation","unknown"], "Underground forum moderator. Manages reputation systems and vendor verification for darkweb markets. High standing in cybercriminal community. Linked to credential sales.", 84, True, None),
    ("Pavel Sergeev (Bulletproof Hosting)", ["vpn-service","anonymization","bulletproof-hosting","infrastructure","russian"], "Bulletproof hosting and VPN service operator. Provides anonymous infrastructure for threat actors including C2 servers at 198.51.100.50, 203.0.113.200. No DMCA or law enforcement compliance.", 88, True, None),
    ("Jin-Ho Park (Browser Extension Malware)", ["browser-extension","chrome","credential-harvest","browser-stealer","south-korean"], "Malicious browser extension developer. Creates Chrome extensions that harvest credentials and cookies. Linked to Google Demo and Amazon Demo credential theft.", 83, True, None),
    ("Robert Anderson (Suspected Insider)", ["suspected-insider","financial","fraud","investigation","american"], "Suspected insider at financial institution. Under investigation for providing internal access to external threat actors. Linked to JPMorgan Demo Bank compromise.", 78, True, None),
    ("Marcus Webb (Cobalt Strike Operator)", ["cobalt-strike","c2-framework","pentest-tool","abuse","american"], "Cobalt Strike C2 framework operator. Uses pentest tool for malicious purposes against demo companies. Linked to lateral movement in MetaCorp and JPMorgan Demo networks.", 90, True, None),
    ("Andrei Popescu (Emotet Distributor)", ["emotet","malware-distributor","loader","spam","romanian"], "Emotet malware distributor. Manages Emotet botnet and distributes banking trojans via malicious documents. Linked to JPMorgan Demo and PayPal Demo initial access.", 86, True, None),
    ("Liam O'Brien (Credential Stuffing)", ["credential-stuffing","account-takeover","automation","scaling","irish"], "Credential stuffing operator. Runs automated attacks against streaming platforms and social media using leaked credential combos. Linked to Netflix Demo and Spotify Demo compromise.", 84, True, None),
    ("Agent Alpha (Undercover Researcher)", ["undercover","osint","darkweb-research","investigation","unknown"], "Undercover OSINT researcher investigating darkweb markets. Gathering intelligence on threat actors and data breach sellers. Anonymous persona.", 70, False, None),
    ("Satoshi Demo (Crypto Exchange Hacker)", ["crypto-exchange","hack","exchange-breach","fund-theft","japanese"], "Cryptocurrency exchange hacker. Responsible for crypto exchange breaches and fund theft. Linked to SIM swap attacks against financial executives.", 93, True, None),
    ("Nina Volkov (Social Engineering)", ["social-engineering","spear-phishing","pretexting","vishing","russian"], "Social engineering specialist. Conducts spear-phishing, vishing, and pretexting attacks against corporate executives. Linked to BEC operations and credential harvesting.", 88, True, None),
    ("Tomasz Kowalski (Hardware Implant Dev)", ["hardware-implant","firmware","supply-chain","backdoor","polish"], "Hardware implant and firmware backdoor developer. Creates malicious hardware for supply chain attacks. Targets enterprise hardware suppliers.", 92, True, None),
    ("Alexis Dubois (Document Malware Dev)", ["macro-malware","document-malware","office-exploit","phishing-lure","french"], "Office document macro malware developer. Creates malicious Word and Excel documents for phishing campaigns. CVE-2026-99992 distributed via document lures.", 85, True, None),
    ("Viktor Kozlov (Ransomware Affiliate Mgr)", ["ransomware","affiliate-manager","raas","program-operator","russian"], "Ransomware affiliate program manager. Manages DEMO-RANSOM-01 affiliate network, recruits affiliates, provides malware updates and infrastructure support.", 95, True, None),
    ("Mei Lin (Cloud Infrastructure Attacker)", ["cloud-attacker","aws","gcp","azure","infrastructure-hack","chinese"], "Cloud infrastructure attack specialist. Targets AWS, GCP, and Azure environments. Responsible for Google Demo GCP and Amazon Demo AWS breaches via NEXUS-THREAT group.", 87, True, None),
    ("Carmen Rivera (Tax Fraud Specialist)", ["tax-fraud","identity-theft","financial-crime","document-forgery","spanish"], "Tax fraud and identity theft specialist. Creates fake identities using stolen PII from breach data. Linked to financial account takeover operations.", 79, True, None),
    ("Boris Volkov (Spam Botnet Operator)", ["spam","botnet","email-campaign","phishing-scale","russian"], "Spam botnet operator. Manages large email spam infrastructure for phishing campaigns and malware distribution. Linked to phishing lures targeting MetaCorp and Google Demo employees.", 82, True, None),
    ("Hiroshi Tanaka (AI Phishing Developer)", ["ai-phishing","llm-tools","social-engineering","automation","japanese"], "AI-powered phishing tool developer. Uses LLMs to generate personalized phishing content at scale. Automated spear-phishing campaigns against financial sector executives.", 85, True, None),
    ("Jake Wilson (Gaming Cheat Developer)", ["game-cheat","malware","steam","account-theft","american"], "Gaming cheat and malware developer. Creates Steam account theft tools and game exploits. Linked to CYBER-SHADOW group targeting gaming platforms.", 73, True, None),
    ("Grace Adeyemi (Charity Fraud Actor)", ["charity-fraud","scam","social-engineering","donation-theft","nigerian"], "Charity fraud and social engineering specialist. Uses fake personas and emotional manipulation to steal donations and credentials. Linked to BEC operations.", 76, True, None),
    ("Ankur Sharma (Tech Support Scam Op)", ["tech-support-scam","social-engineering","impersonation","fraud","indian"], "Tech support scam operator. Runs phone and web-based tech support scams impersonating Microsoft, Google, and Amazon support. Linked to credential theft.", 80, True, None),
    ("Chioma Eze (Romance Scam Operator)", ["romance-scam","social-engineering","catfishing","fraud","nigerian"], "Romance scam and catfishing operator. Creates fake personas to build relationships and extract money or credentials. Part of larger financial fraud network.", 74, True, None),
    ("Agent Delta (Law Enforcement Undercover)", ["law-enforcement","darkweb-investigator","undercover","le-ad","american"], "Undercover law enforcement agent investigating darkweb markets and threat actors. Gathering evidence on credential sales and data breaches.", 55, False, None),
    ("Julia Chen (Corporate Espionage)", ["corporate-espionage","competitor","industrial-spy","insider","chinese"], "Corporate espionage actor. Conducts industrial espionage against technology and finance companies. Uses insider access and social engineering to steal trade secrets.", 88, True, None),
    ("Marcus Reed (Ambiguous Whistleblower)", ["whistleblower","insider","ambiguous","investigation","american"], "Ambiguous figure claiming to be a whistleblower with access to internal security data. Under investigation to determine if legitimate or threat actor cover story.", 68, False, None),
    ("Kai Zhang (DDoS Extortion Actor)", ["ddos-extortion","ransom-ddos","group-nexus","denial-of-service","chinese"], "DDoS extortion actor. Conducts Ransom DDoS attacks against streaming platforms and financial institutions. Demands payment to stop attacks.", 86, True, None),
    ("Artem Koval (Rootkit Developer)", ["rootkit","kernel-level","persistence","stealth-malware","ukrainian"], "Rootkit and kernel-level malware developer. Creates persistent stealth malware for long-term access. Linked to APT groups requiring stealthy intrusion capabilities.", 91, True, None),
    ("Daniel Foster (Investment Fraud)", ["ponzi","investment-fraud","startup-scam","financial-crime","british"], "Investment fraud and Ponzi scheme operator. Uses fake startups and stolen identity data to defraud investors. Linked to cryptocurrency theft operations.", 77, True, None),
    ("Viktor Petrov (Chrome Extension Malware)", ["chrome-extension","browser-hijack","adware","credential-steal","russian"], "Malicious Chrome extension author. Creates browser hijackers and credential-stealing extensions distributed via Chrome Web Store. Linked to Google Demo credential theft.", 80, True, None),
    ("Wei Li (Malicious DeFi Auditor)", ["smart-contract","audit-fraud","defi-exploit","crypto-scam","chinese"], "Malicious DeFi smart contract auditor. Conducts fake audits then exploits vulnerabilities in DeFi protocols. Linked to cryptocurrency theft from defi projects.", 83, True, None),
    ("Olga Sergeeva (Supply Chain Poisoner)", ["supply-chain","package-poisoning","npm-pypi","open-source-tamper","russian"], "Supply chain package poisoner. Tampers with NPM and PyPI open-source packages to inject malware. Targets developers at Google Demo, Amazon Demo, and Microsoft Demo.", 89, True, None),
    ("Ivan Volkov (Disinformation Operator)", ["disinformation","fake-news","influence-op","social-media-manipulation","russian"], "Disinformation and influence operation specialist. Runs social media manipulation campaigns and fake news operations. Linked to state-sponsored influence operations.", 82, True, None),
    ("Yosef Cohen (Malvertising Operator)", ["malvertising","ad-network","malware-distribution","drive-by-download","israeli"], "Malvertising network operator. Runs malicious advertising campaigns distributing malware via ad networks. Drive-by downloads and exploit kit redirects.", 84, True, None),
    ("Zara Ahmed (Biometric Data Exploiter)", ["biometric-theft","facial-recognition","data-breach","privacy","pakistani"], "Biometric data exploitation specialist. Steals and trades facial recognition data and biometric information from data breaches. Linked to identity fraud operations.", 81, True, None),
]

output = []
output.append('-- ============================================================')
output.append('-- FACE SEARCH DEMO IDENTITIES - IntelForge FYP')
output.append('-- 120 synthetic identities matching actual table schema')
output.append('-- Run via: docker exec -i intelforge-postgres psql -U intelforge -d intelforge < seed-face-identities-demo.sql')
output.append('-- ============================================================')
output.append('')

for idx, (name, tags, notes, score, watchlist, thread) in enumerate(identities):
    name_esc = name.replace("'", "''")
    notes_esc = notes.replace("'", "''")
    tags_sql = 'ARRAY[' + ','.join(f"'{t}'" for t in tags) + ']::text[]'
    thread_sql = f"'{thread}'" if thread else 'NULL'
    watchlist_sql = 'true' if watchlist else 'false'
    days_offset = 120 - idx
    output.append(f"INSERT INTO face_identities (name, tags, notes, threat_score, is_watchlist, threads_username, created_by, created_at)")
    output.append(f"VALUES ('{name_esc}', {tags_sql}, '{notes_esc}', {score}, {watchlist_sql}, {thread_sql}, 'demo-system', NOW()-INTERVAL '{days_offset} days')")
    output.append("ON CONFLICT (name) DO NOTHING;")
    output.append('')

sql = '\n'.join(output)
print(f'Generated {len(identities)} identity INSERTs, {len(sql):,} chars')
open(r'C:\Users\Hp\Desktop\FYP\code\scripts\seed-face-identities-demo.sql', 'w').write(sql)
print('Written to seed-face-identities-demo.sql')
