-- Seed intel_demo_corpus table for search functionality
-- All data is 100% synthetic/fictional
-- Run via: Get-Content seed-intel-demo-corpus.sql | docker exec -i intelforge-postgres psql -U intelforge -d intelforge

BEGIN;

INSERT INTO intel_demo_corpus (id, timestamp, doc_type, source_name, source_kind, title, summary, body, severity, risk_score, confidence, tlp, tags, entities, iocs, relationships, raw_reference, safe_demo, redaction_level)
VALUES
  -- MetaCorp breach entries
  ('demo-evt-meta-001', NOW()-INTERVAL '45 days', 'breach', 'Demo Feed', 'synthetic', 'MetaCorp confirms 2.9B record breach — largest social media leak in history', 'MetaCorp platform database containing 2.9 billion user records posted on darkweb forum.', 'MetaCorp platform database containing 2.9 billion user records posted on darkweb forum. Data includes emails, hashed passwords, phone numbers, and profile IDs. Demo dataset. Breach vector: CVE-2026-99001 (MetaCorp Fileshare Pro RCE). Threat actor: DEMO-APT-01 linked via stealer logs (Raccoon). C2: 198.51.100.50.', 'critical', 95, 92, 'TLP:CLEAR', ARRAY['meta','breach','social-media','2.9b-records','demo'], jsonb_build_array(jsonb_build_object('type','domain','value','meta-corp.invalid'),jsonb_build_object('type','domain','value','facebook-demo.invalid'),jsonb_build_object('type','cve','value','CVE-2026-99001'),jsonb_build_object('type','actor','value','DEMO-APT-01')), jsonb_build_array(jsonb_build_object('type','domain','value','meta-corp.invalid'),jsonb_build_object('type','ip','value','198.51.100.50')), jsonb_build_array(jsonb_build_object('type','attributed_to','value','DEMO-APT-01'),jsonb_build_object('type','exploits_cve','value','CVE-2026-99001')), '{}'::jsonb, true, 'synthetic'),

  ('demo-evt-meta-002', NOW()-INTERVAL '43 days', 'ioc', 'Demo Feed', 'synthetic', 'MetaCorp breach IOCs: domain meta-corp.invalid, IP 198.51.100.50, hash deadbeef...', 'Indicators of compromise from MetaCorp breach linked to threat actor DEMO-APT-01.', 'IOCs from MetaCorp breach: domain=meta-corp.invalid, IP=198.51.100.50 (C2 server), SHA256=deadbeef0000000000000000000000000000000000000000000000000000000001 (meta_webshell.php), malware_family=DEMO-WEBSHELL-01. Linked to CVE-2026-99001 exploitation. Stealer logs captured admin credentials 6 days before breach.', 'critical', 93, 95, 'TLP:CLEAR', ARRAY['meta','ioc','c2','malware','demo'], jsonb_build_array(jsonb_build_object('type','domain','value','meta-corp.invalid'),jsonb_build_object('type','ip','value','198.51.100.50'),jsonb_build_object('type','sha256','value','deadbeef0000000000000000000000000000000000000000000000000000000001'),jsonb_build_object('type','malware','value','DEMO-WEBSHELL-01')), jsonb_build_array(jsonb_build_object('type','domain','value','meta-corp.invalid'),jsonb_build_object('type','ip','value','198.51.100.50')), jsonb_build_array(jsonb_build_object('type','c2_for','value','meta-corp.invalid')), '{}'::jsonb, true, 'synthetic'),

  ('demo-evt-meta-003', NOW()-INTERVAL '44 days', 'vulnerability', 'Demo Feed', 'synthetic', 'CVE-2026-99001: MetaCorp Fileshare Pro remote code execution via unauthenticated file upload', 'Critical RCE vulnerability in MetaCorp Fileshare Pro actively exploited by DEMO-APT-01 and DEMO-RANSOM-01.', 'CVE-2026-99001 affects MetaCorp Fileshare Pro. CVSS 9.8 CRITICAL. Unauthenticated file upload via /api/upload endpoint allows remote code execution. Webshell drops at /uploads/shell.php. Actively exploited by DEMO-APT-01 for MetaCorp breach and by DEMO-RANSOM-01 for double-extortion. Added to CISA KEV catalog.', 'critical', 98, 97, 'TLP:CLEAR', ARRAY['cve','meta','rce','exploit','kev','demo'], jsonb_build_array(jsonb_build_object('type','cve','value','CVE-2026-99001'),jsonb_build_object('type','vendor','value','MetaCorp'),jsonb_build_object('type','product','value','FileShare Pro'),jsonb_build_object('type','actor','value','DEMO-APT-01'),jsonb_build_object('type','actor','value','DEMO-RANSOM-01')), jsonb_build_array(jsonb_build_object('type','cve','value','CVE-2026-99001')), jsonb_build_array(jsonb_build_object('type','exploited_by','value','DEMO-APT-01'),jsonb_build_object('type','exploited_by','value','DEMO-RANSOM-01')), '{"cvss_v3_score":9.8,"cvss_v3_severity":"CRITICAL","epss_score":0.96,"is_kev":true}'::jsonb, true, 'synthetic'),

  ('demo-evt-meta-004', NOW()-INTERVAL '44 days', 'stealer', 'Demo Feed', 'synthetic', 'Stealer logs show MetaCorp credentials harvested before breach', 'Raccoon stealer captured MetaCorp employee credentials 6 days before the breach.', 'Stealer telemetry from meta-host-001 (Windows 11, US): Raccoon stealer captured 234 credentials including admin.meta@demo.invalid, dev.team@demo.invalid, cloudops@demo.invalid. VPN portal (vpn.meta-corp.invalid), FileShare admin (fileshare.meta-corp.invalid), and cloud dashboard (cloud.meta-corp.invalid) credentials captured. These were used as initial access for CVE-2026-99001 exploitation.', 'high', 88, 93, 'TLP:CLEAR', ARRAY['stealer','meta','raccoon','credentials','demo'], jsonb_build_array(jsonb_build_object('type','domain','value','meta-corp.invalid'),jsonb_build_object('type','stealer','value','raccoon'),jsonb_build_object('type','cve','value','CVE-2026-99001')), jsonb_build_array(jsonb_build_object('type','domain','value','meta-corp.invalid'),jsonb_build_object('type','ip','value','198.51.100.50')), jsonb_build_array(jsonb_build_object('type','harvested_credentials_for','value','meta-corp.invalid')), '{"stealer_family":"raccoon","credential_count":234,"matched_domains":["meta-corp.invalid","facebook-demo.invalid","instagram-demo.invalid"]}'::jsonb, true, 'masked'),

  -- JPMorgan Demo entries
  ('demo-evt-jpm-001', NOW()-INTERVAL '35 days', 'breach', 'Demo Feed', 'synthetic', 'JPMorgan Demo Bank internal network access confirmed compromised', 'ALPHV/BlackCat ransomware group claims access to JPMorgan Demo Bank internal network.', 'JPMorgan Demo Bank internal network compromised by ALPHV/BlackCat. Full internal network access confirmed. Can access trading systems (trading.jpmorgan-demo.invalid), risk dashboards (risk.jpmorgan-demo.invalid), and internal communications. Bloomberg Terminal credentials captured from Vidar stealer logs (jpm-host-002). Domain admin from jpm-host-003 (raccoon, 298 creds). Darkweb auction started at $75K.', 'critical', 96, 95, 'TLP:CLEAR', ARRAY['jpmorgan','breach','financial','alphv','trading','demo'], jsonb_build_array(jsonb_build_object('type','domain','value','jpmorgan-demo.invalid'),jsonb_build_object('type','actor','value','ALPHV/BlackCat'),jsonb_build_object('type','cve','value','CVE-2026-99992')), jsonb_build_array(jsonb_build_object('type','domain','value','jpmorgan-demo.invalid'),jsonb_build_object('type','ip','value','203.0.113.200')), jsonb_build_array(jsonb_build_object('type','victim_of','value','ALPHV/BlackCat'),jsonb_build_object('type','compromised_by','value','raccoon-stealer')), '{}'::jsonb, true, 'synthetic'),

  ('demo-evt-jpm-002', NOW()-INTERVAL '34 days', 'stealer', 'Demo Feed', 'synthetic', 'Vidar stealer captures JPMorgan Demo trading credentials', '6 compromised hosts in JPMorgan Demo environment captured sensitive trading credentials.', 'Vidar stealer logs from jpm-host-002 (Windows 11, US): trader.senior@demo.invalid captured from trading.jpmorgan-demo.invalid. Bloomberg Terminal session cookies harvested. jpm-host-004 (RedLine): bloomberg.user@demo.invalid from bloomberg.jpmorgan-demo.invalid. jpm-host-003 (Raccoon): it.operations@demo.invalid from intranet.jpmorgan-demo.invalid. Domain admin level access confirmed. jpm-host-006 (Stealc): api.trading@demo.invalid from api.jpmorgan-demo.invalid.', 'high', 90, 92, 'TLP:CLEAR', ARRAY['stealer','vidar','jpmorgan','trading','bloomberg','demo'], jsonb_build_array(jsonb_build_object('type','domain','value','jpmorgan-demo.invalid'),jsonb_build_object('type','stealer','value','vidar')), jsonb_build_array(jsonb_build_object('type','domain','value','jpmorgan-demo.invalid')), jsonb_build_array(jsonb_build_object('type','captured_credentials_from','value','jpmorgan-demo.invalid')), '{"stealer_family":"vidar","credential_count":145,"matched_domains":["jpmorgan-demo.invalid","portal.jpmorgan-demo.invalid"]}'::jsonb, true, 'masked'),

  ('demo-evt-jpm-003', NOW()-INTERVAL '40 days', 'vulnerability', 'Demo Feed', 'synthetic', 'CVE-2026-99992: JPMorgan Demo trading platform SQL injection', 'Critical SQL injection in JPMorgan Demo trading platform exploited by DEMO-APT-02.', 'CVE-2026-99992 affects JPMorgan Demo trading platform. CVSS 9.1 CRITICAL. SQL injection in order submission endpoint allows database access. Linked to JPMorgan Demo Bank breach by DEMO-APT-02 actor. Exploit: order parameter not sanitized, UNION-based injection returns full DB. ALPHV/BlackCat used this as initial access vector.', 'critical', 97, 94, 'TLP:CLEAR', ARRAY['cve','jpmorgan','sql-injection','trading','demo'], jsonb_build_array(jsonb_build_object('type','cve','value','CVE-2026-99992'),jsonb_build_object('type','vendor','value','JPMorgan'),jsonb_build_object('type','product','value','Trading Platform'),jsonb_build_object('type','actor','value','DEMO-APT-02'),jsonb_build_object('type','actor','value','ALPHV/BlackCat')), jsonb_build_array(jsonb_build_object('type','cve','value','CVE-2026-99992')), jsonb_build_array(jsonb_build_object('type','exploited_by','value','DEMO-APT-02'),jsonb_build_object('type','exploited_by','value','ALPHV/BlackCat')), '{"cvss_v3_score":9.1,"cvss_v3_severity":"CRITICAL","epss_score":0.89,"is_kev":true}'::jsonb, true, 'synthetic'),

  -- Google Demo entries
  ('demo-evt-google-001', NOW()-INTERVAL '55 days', 'cloud_exposure', 'Demo Feed', 'synthetic', 'Google Demo GCP service account keys exposed on GitHub and darkweb', 'NEXUS-THREAT group exploiting Google Demo cloud environment via exposed service account keys.', 'Google Demo GCP service account keys found exposed: gh-google-001: CDK pipeline in google-demo-infrastructure/terraform (gcp_service_account_key, critical, still exposed). gh-google-002: prod.env in google-demo-config/cloud-run (google_api_key, high). gh-google-003: train.py in google-demo-ml/pipeline (google_oauth_token, critical). NEXUS-STEALER-01 (google_stealer.py) captures GCP credentials and beacons to 198.51.100.75. C2 beacon pattern detected in google-host-001.', 'high', 88, 91, 'TLP:CLEAR', ARRAY['google','gcp','cloud','nexus-threat','github','demo'], jsonb_build_array(jsonb_build_object('type','domain','value','google-demo.invalid'),jsonb_build_object('type','ip','value','198.51.100.75'),jsonb_build_object('type','actor','value','NEXUS-THREAT'),jsonb_build_object('type','malware','value','NEXUS-STEALER-01')), jsonb_build_array(jsonb_build_object('type','domain','value','google-demo.invalid'),jsonb_build_object('type','ip','value','198.51.100.75')), jsonb_build_array(jsonb_build_object('type','compromised_by','value','NEXUS-THREAT'),jsonb_build_object('type','exposed_on','value','github')), '{"github_repo":"google-demo-infrastructure","secret_type":"gcp_service_account_key","risk_level":"critical","still_exposed":true}'::jsonb, true, 'synthetic'),

  -- Microsoft Demo entries
  ('demo-evt-ms-001', NOW()-INTERVAL '48 days', 'breach', 'Demo Feed', 'synthetic', 'Microsoft Demo Azure AD global admin credentials found in darkweb market', 'LockBit ransomware affiliate selling Microsoft Demo Azure AD global admin access.', 'Microsoft Demo Azure AD global admin credentials for microsoft-demo.invalid tenant found in darkweb market (LockBit affiliate). admin@microsoft-demo.invalid password captured by Raccoon stealer (ms-host-001). Can access Azure Portal, DevOps, and all SaaS apps. tenant_id=DEMO-CORP. LockBit affiliate started auction at $20K. DevOps credentials (devops@microsoft-demo.invalid) from RedLine (ms-host-002) give Project Collection Admin access.', 'critical', 94, 93, 'TLP:CLEAR', ARRAY['microsoft','azure','lockbit','global-admin','demo'], jsonb_build_array(jsonb_build_object('type','domain','value','microsoft-demo.invalid'),jsonb_build_object('type','actor','value','LockBit'),jsonb_build_object('type','cve','value','CVE-2026-99993')), jsonb_build_array(jsonb_build_object('type','domain','value','microsoft-demo.invalid')), jsonb_build_array(jsonb_build_object('type','victim_of','value','LockBit'),jsonb_build_object('type','compromised_by','value','raccoon-stealer')), '{}'::jsonb, true, 'synthetic'),

  -- Amazon Demo entries
  ('demo-evt-aws-001', NOW()-INTERVAL '50 days', 'cloud_exposure', 'Demo Feed', 'synthetic', 'Amazon Demo AWS credentials with AdministratorAccess policy exposed', 'NEXUS-THREAT group targeting Amazon Demo AWS environment via exposed credentials.', 'Amazon Demo AWS credentials exposed: Root account (Christopher Lee) credentials found in paste site and Stealc stealer. Full AWS account access, no MFA. gh-aws-001: CDK pipeline in amazon-demo-infra/cdk-pipeline (aws_access_key, critical, still exposed). gh-aws-002: deploy.yml in amazon-demo-cicd/pipeline (aws_secret_key, critical). NEXUS-STEALER-02 (aws_keylogger.exe) targets AWS credentials and beacons to 198.51.100.100. Full cloud environment compromise confirmed.', 'critical', 92, 90, 'TLP:CLEAR', ARRAY['amazon','aws','nexus-threat','cloud','root-account','demo'], jsonb_build_array(jsonb_build_object('type','domain','value','amazon-demo.invalid'),jsonb_build_object('type','ip','value','198.51.100.100'),jsonb_build_object('type','actor','value','NEXUS-THREAT')), jsonb_build_array(jsonb_build_object('type','domain','value','amazon-demo.invalid'),jsonb_build_object('type','ip','value','198.51.100.100')), jsonb_build_array(jsonb_build_object('type','compromised_by','value','NEXUS-THREAT')), '{"aws_access_type":"AdministratorAccess","region":"us-east-1","root_compromised":true}'::jsonb, true, 'synthetic'),

  -- Cross-company APT campaigns
  ('demo-evt-apt-001', NOW()-INTERVAL '30 days', 'apt', 'Demo Feed', 'synthetic', 'DEMO-APT-01 campaign targets financial and tech sectors with multi-stage attack', 'Threat actor DEMO-APT-01 conducting coordinated campaign against MetaCorp, JPMorgan Demo, and Microsoft Demo.', 'CTI Advisory: DEMO-APT-01 threat group targeting financial and technology sectors using multi-stage attack chain. VICTIMS: MetaCorp Inc (2.9B records via CVE-2026-99001), JPMorgan Demo Bank (internal network via CVE-2026-99992), Microsoft Demo (Azure AD via CVE-2026-99993). ATTACK CHAIN: Phishing (CVE-2026-99001) -> webshell (DEMO-WEBSHELL-01) -> stealer (Raccoon) -> credentials -> lateral movement -> data exfiltration. IOCs: 198.51.100.50 (meta C2), 203.0.113.200 (jpm C2).', 'critical', 96, 95, 'TLP:CLEAR', ARRAY['apt','demo-apt-01','campaign','multi-stage','meta','jpmorgan','microsoft','demo'], jsonb_build_array(jsonb_build_object('type','actor','value','DEMO-APT-01'),jsonb_build_object('type','domain','value','meta-corp.invalid'),jsonb_build_object('type','domain','value','jpmorgan-demo.invalid'),jsonb_build_object('type','domain','value','microsoft-demo.invalid'),jsonb_build_object('type','ip','value','198.51.100.50'),jsonb_build_object('type','ip','value','203.0.113.200'),jsonb_build_object('type','cve','value','CVE-2026-99001'),jsonb_build_object('type','cve','value','CVE-2026-99992'),jsonb_build_object('type','cve','value','CVE-2026-99993')), jsonb_build_array(jsonb_build_object('type','ip','value','198.51.100.50'),jsonb_build_object('type','ip','value','203.0.113.200')), jsonb_build_array(jsonb_build_object('type','targets','value','meta-corp.invalid'),jsonb_build_object('type','targets','value','jpmorgan-demo.invalid'),jsonb_build_object('type','targets','value','microsoft-demo.invalid')), '{"advisory_id":"DEMO-ADV-2026-001","attack_chain":["phishing","webshell","stealer","lateral-movement","data-exfil"]}'::jsonb, true, 'synthetic'),

  ('demo-evt-nexus-001', NOW()-INTERVAL '25 days', 'apt', 'Demo Feed', 'synthetic', 'NEXUS-THREAT abusing cloud trust relationships for cross-account access', 'NEXUS-THREAT group exploiting trust relationships between cloud accounts at Google Demo and Amazon Demo.', 'CTI Advisory: NEXUS-THREAT group exploiting trust relationships between GCP and AWS cloud accounts. Google Demo service account keys used to pivot to Amazon Demo AWS environment via shared OAuth patterns. MALWARE: NEXUS-STEALER-01 (google_stealer.py) and NEXUS-STEALER-02 (aws_keylogger.exe) both beacon to 198.51.100.75. GITHUB EXPOSURE: gh-google-001 (GCP key), gh-aws-001 (AWS key). DARKWEB: NEXUS-THREAT selling cloud access on versus_market and torrez_market.', 'critical', 94, 92, 'TLP:CLEAR', ARRAY['apt','nexus-threat','cloud','gcp','aws','cross-cloud','demo'], jsonb_build_array(jsonb_build_object('type','actor','value','NEXUS-THREAT'),jsonb_build_object('type','domain','value','google-demo.invalid'),jsonb_build_object('type','domain','value','amazon-demo.invalid'),jsonb_build_object('type','ip','value','198.51.100.75')), jsonb_build_array(jsonb_build_object('type','ip','value','198.51.100.75')), jsonb_build_array(jsonb_build_object('type','targets','value','google-demo.invalid'),jsonb_build_object('type','targets','value','amazon-demo.invalid')), '{}'::jsonb, true, 'synthetic'),

  -- Ransomware groups
  ('demo-evt-ransom-001', NOW()-INTERVAL '15 days', 'ransomware', 'Demo Feed', 'synthetic', 'DEMO-RANSOM-01 adds 3 new victims to leak site', 'Ransomware group DEMO-RANSOM-01 listed MetaCorp Inc, JPMorgan Demo Bank, and Steam Demo on darkweb leak site.', 'DEMO-RANSOM-01 (DeadboltDemo/LockIT) ransomware group expanded leak site with 3 new victims: 1) MetaCorp Inc - 2.9B records, ransom $5M, 2) JPMorgan Demo Bank - internal network access, ransom $3M, 3) Steam Demo Inc - 15M gaming accounts, ransom $500K. Demands range from $500K to $5M. Double-extortion model confirmed. LockIT ransomware builder used. C2: ransom-demo.onion.', 'critical', 93, 91, 'TLP:CLEAR', ARRAY['ransomware','demo-ransom-01','meta','jpmorgan','steam','leak-site','demo'], jsonb_build_array(jsonb_build_object('type','actor','value','DEMO-RANSOM-01'),jsonb_build_object('type','domain','value','meta-corp.invalid'),jsonb_build_object('type','domain','value','jpmorgan-demo.invalid'),jsonb_build_object('type','domain','value','steam-demo.invalid')), jsonb_build_array(jsonb_build_object('type','domain','value','meta-corp.invalid')), jsonb_build_array(jsonb_build_object('type','claims_victim','value','MetaCorp Inc'),jsonb_build_object('type','claims_victim','value','JPMorgan Demo Bank'),jsonb_build_object('type','claims_victim','value','Steam Demo Inc')), '{}'::jsonb, true, 'synthetic'),

  -- Combolist mega drop
  ('demo-evt-combo-001', NOW()-INTERVAL '10 days', 'combolist', 'Demo Feed', 'synthetic', 'Full cross-platform mega combo links all demo companies - 2M lines', '2 million line combolist compiled by DEMO-APT-01 linking credentials across all 15 demo companies.', 'Mega combo list (2M lines) compiled by DEMO-APT-01. Links credentials across all demo platforms: MetaCorp (meta-corp.invalid, 500K lines), Google (google-demo.invalid, 200K lines), Amazon (amazon-demo.invalid, 150K lines), Microsoft (microsoft-demo.invalid, 180K lines), JPMorgan (jpmorgan-demo.invalid, 100K lines), TikTok (tiktok-demo.invalid, 250K lines), Apple (apple-demo.invalid, 200K lines), Netflix (netflix-demo.invalid, 80K lines), Spotify (spotify-demo.invalid, 60K lines), PayPal (paypal-demo.invalid, 90K lines), LinkedIn (linkedin-demo.invalid, 120K lines), Steam (steam-demo.invalid, 40K lines), Uber (uber-demo.invalid, 30K lines), Salesforce (salesforce-demo.invalid, 35K lines). Format: email:pass@domain | Platform | verified=true. Distributed via Telegram @ShadowBroker channel (8000 members).', 'critical', 92, 94, 'TLP:CLEAR', ARRAY['combolist','mega-combo','2m-lines','telegram','demo-apt-01','all-platforms','demo'], jsonb_build_array(jsonb_build_object('type','domain','value','meta-corp.invalid'),jsonb_build_object('type','domain','value','google-demo.invalid'),jsonb_build_object('type','domain','value','amazon-demo.invalid'),jsonb_build_object('type','domain','value','microsoft-demo.invalid'),jsonb_build_object('type','actor','value','DEMO-APT-01')), jsonb_build_array(jsonb_build_object('type','domain','value','meta-corp.invalid')), jsonb_build_array(jsonb_build_object('type','source','value','telegram-@ShadowBroker')), '{"line_count":2000000,"unique_domains":15,"source":"telegram","threat_actor":"DEMO-APT-01"}'::jsonb, true, 'synthetic'),

  -- Malware samples
  ('demo-evt-mal-001', NOW()-INTERVAL '45 days', 'malware', 'Demo Feed', 'synthetic', 'DEMO-WEBSHELL-01 linked to MetaCorp breach via CVE-2026-99001', 'Webshell used in MetaCorp breach identified as DEMO-WEBSHELL-01.', 'Malware sample: meta_webshell.php (SHA256: deadbeef0000000000000000000000000000000000000000000000000000000001). Family: DEMO-WEBSHELL-01. Used in MetaCorp breach via CVE-2026-99001 exploitation. Uploaded via /api/upload endpoint without authentication. Webshell at /uploads/shell.php allows RCE. C2: 198.51.100.50. Linked to DEMO-APT-01 and DEMO-RANSOM-01. Source: malwarebazaar.', 'high', 89, 94, 'TLP:CLEAR', ARRAY['malware','webshell','meta','cve-2026-99001','demo'], jsonb_build_array(jsonb_build_object('type','sha256','value','deadbeef0000000000000000000000000000000000000000000000000000000001'),jsonb_build_object('type','domain','value','meta-corp.invalid'),jsonb_build_object('type','ip','value','198.51.100.50'),jsonb_build_object('type','actor','value','DEMO-APT-01')), jsonb_build_array(jsonb_build_object('type','sha256','value','deadbeef0000000000000000000000000000000000000000000000000000000001'),jsonb_build_object('type','domain','value','meta-corp.invalid')), jsonb_build_array(jsonb_build_object('type','used_in','value','meta-corp.invalid')), '{"file_type":"php","malware_family":"DEMO-WEBSHELL-01","source":"malwarebazaar"}'::jsonb, true, 'synthetic'),

  -- Phishing campaigns
  ('demo-evt-phish-001', NOW()-INTERVAL '44 days', 'phishing', 'Demo Feed', 'synthetic', 'Phishing campaign impersonates MetaCorp with credential harvesting kit', 'Phishing kit targeting MetaCorp credentials hosted at 198.51.100.50.', 'Phishing URL: https://secure-meta-login.invalid/auth/signin targeting MetaCorp users. Hosting IP: 198.51.100.50 (Russia). Sender: noreply@meta-corp-verify.invalid. Credential harvesting kit impersonates MetaCorp login page. Captures email and password, sends to C2 at 198.51.100.50. Multiple similar phishing URLs detected: meta-corp-verify.invalid/account, secure-meta-login.invalid/auth/signin. Linked to DEMO-APT-01 campaign. Source: openphish, phishtank.', 'high', 82, 90, 'TLP:CLEAR', ARRAY['phishing','meta','credential-harvesting','impersonation','demo'], jsonb_build_array(jsonb_build_object('type','domain','value','meta-corp.invalid'),jsonb_build_object('type','domain','value','secure-meta-login.invalid'),jsonb_build_object('type','ip','value','198.51.100.50')), jsonb_build_array(jsonb_build_object('type','domain','value','secure-meta-login.invalid'),jsonb_build_object('type','ip','value','198.51.100.50')), jsonb_build_array(jsonb_build_object('type','impersonates','value','MetaCorp')), '{"target_brand":"MetaCorp","phish_type":"credential_harvesting","active":true}'::jsonb, true, 'synthetic'),

  -- Actor profiles
  ('demo-evt-actor-001', NOW()-INTERVAL '120 days', 'apt', 'Demo Feed', 'synthetic', 'DEMO-APT-01 threat actor profile: ransomware and data theft specialist', 'Detailed profile of threat actor DEMO-APT-01.', 'Threat Actor Profile: DEMO-APT-01 (aliases: ShadowForge, IronWave). Prolific threat actor specializing in ransomware and data theft. TARGET SECTORS: Technology, Financial, Healthcare, Government. COUNTRIES: Russia, China. LINKED BREACHES: MetaCorp Inc (2.9B records), JPMorgan Demo Bank (internal network), Microsoft Demo Corp (Azure AD), Amazon Demo Inc (AWS). EXPLOITED CVES: CVE-2026-99001 (MetaCorp Fileshare Pro RCE), CVE-2026-99991 (Google Workspace SSO bypass). MALWARE: DEMO-WEBSHELL-01, DEMO-BACKDOOR-01, DEMO-LATERAL-01. IOCs: 198.51.100.50 (C2), 203.0.113.200 (C2). ATTACK METHODS: Phishing, exploit exploitation, stealer malware (Raccoon, Lumma), lateral movement.', 'high', 91, 95, 'TLP:CLEAR', ARRAY['apt','demo-apt-01','threat-actor','ransomware','profile','demo'], jsonb_build_array(jsonb_build_object('type','actor','value','DEMO-APT-01'),jsonb_build_object('type','cve','value','CVE-2026-99001'),jsonb_build_object('type','cve','value','CVE-2026-99991'),jsonb_build_object('type','malware','value','DEMO-WEBSHELL-01'),jsonb_build_object('type','malware','value','DEMO-BACKDOOR-01')), jsonb_build_array(jsonb_build_object('type','ip','value','198.51.100.50'),jsonb_build_object('type','ip','value','203.0.113.200')), jsonb_build_array(jsonb_build_object('type','linked_to','value','meta-corp.invalid'),jsonb_build_object('type','linked_to','value','jpmorgan-demo.invalid'),jsonb_build_object('type','linked_to','value','microsoft-demo.invalid')), '{"aliases":["ShadowForge","IronWave"],"sectors":["Technology","Financial","Healthcare","Government"],"countries":["Russia","China"]}'::jsonb, true, 'synthetic'),

  -- Paste site posts
  ('demo-evt-paste-001', NOW()-INTERVAL '44 days', 'forum_post', 'Demo Feed', 'synthetic', 'Pastebin post exposes MetaCorp admin credentials from Raccoon stealer', 'Admin credentials for MetaCorp VPN found on Pastebin.', 'Pastebin post (paste-meta-001): admin.meta@demo.invalid:<REDACTED_DEMO_PASSWORD> | VPN Portal (vpn.meta-corp.invalid) | Raccoon stealer capture | department=IT. Source: Pastebin. Posted by threat actor. Linked to MetaCorp breach and DEMO-APT-01 campaign. Tags: credential, meta, vpn, stealer.', 'high', 78, 87, 'TLP:CLEAR', ARRAY['paste','meta','credential','vpn','stealer','demo'], jsonb_build_array(jsonb_build_object('type','email','value','admin.meta@demo.invalid'),jsonb_build_object('type','domain','value','meta-corp.invalid')), jsonb_build_array(jsonb_build_object('type','domain','value','meta-corp.invalid')), jsonb_build_array(jsonb_build_object('type','exposes','value','admin.meta@demo.invalid')), '{}'::jsonb, true, 'masked'),

  -- Stealer logs overview
  ('demo-evt-stealer-001', NOW()-INTERVAL '30 days', 'stealer', 'Demo Feed', 'synthetic', 'Multi-stealer campaign captures credentials across all demo companies', 'Raccoon, RedLine, Lumma, Stealc, and Aurora stealer campaigns active across demo environment.', 'Stealer campaign summary: Raccoon (23 hosts, 5,234 creds), RedLine (15 hosts, 3,120 creds), Lumma (18 hosts, 4,567 creds), Stealc (12 hosts, 3,890 creds), Aurora (8 hosts, 1,234 creds), Vidar (6 hosts, 1,890 creds). TARGETED DOMAINS: meta-corp.invalid (10 hosts, 890 creds), jpmorgan-demo.invalid (6 hosts, 445 creds), google-demo.invalid (5 hosts, 340 creds), microsoft-demo.invalid (4 hosts, 298 creds), amazon-demo.invalid (4 hosts, 312 creds), tiktok-demo.invalid (4 hosts, 278 creds). All data synthetic and demonstratic.', 'high', 85, 88, 'TLP:CLEAR', ARRAY['stealer','raccoon','redline','lumma','stealc','credential','demo'], jsonb_build_array(jsonb_build_object('type','stealer','value','raccoon'),jsonb_build_object('type','stealer','value','redline'),jsonb_build_object('type','stealer','value','lumma'),jsonb_build_object('type','stealer','value','stealc'),jsonb_build_object('type','domain','value','meta-corp.invalid'),jsonb_build_object('type','domain','value','jpmorgan-demo.invalid')), jsonb_build_array(jsonb_build_object('type','domain','value','meta-corp.invalid')), jsonb_build_array(jsonb_build_object('type','captures_from','value','meta-corp.invalid'),jsonb_build_object('type','captures_from','value','jpmorgan-demo.invalid'),jsonb_build_object('type','captures_from','value','google-demo.invalid')), '{"total_hosts":82,"total_credentials":20563}'::jsonb, true, 'masked'),

  -- TikTok
  ('demo-evt-tiktok-001', NOW()-INTERVAL '38 days', 'breach', 'Demo Feed', 'synthetic', 'TikTok Demo platform database containing 1.2B user records posted on breach forum', 'Dark web marketplace listing claims TikTok Demo platform database with emails, phone numbers, and hashed passwords.', 'TikTok Demo platform database with 1.2B user records posted on darkweb marketplace (torrez_market, DarkVendor-01). Data: emails, phone numbers, hashed passwords. Creator payment database also leaked (50M creators). Breach vector: CVE-2026-99996 (TikTok Creator API authentication bypass). PHANTOM-SHADOW attributed. Demands 0.04 BTC. Demo dataset.', 'critical', 90, 88, 'TLP:CLEAR', ARRAY['tiktok','breach','1.2b-records','social-media','demo'], jsonb_build_array(jsonb_build_object('type','domain','value','tiktok-demo.invalid'),jsonb_build_object('type','actor','value','PHANTOM-SHADOW'),jsonb_build_object('type','cve','value','CVE-2026-99996')), jsonb_build_array(jsonb_build_object('type','domain','value','tiktok-demo.invalid')), jsonb_build_array(jsonb_build_object('type','victim_of','value','PHANTOM-SHADOW')), '{}'::jsonb, true, 'synthetic'),

  -- Netflix / PHANTOM-SHADOW
  ('demo-evt-netflix-001', NOW()-INTERVAL '40 days', 'breach', 'Demo Feed', 'synthetic', 'Netflix Demo 260M subscriber records leaked by PHANTOM-SHADOW', 'Streaming platform subscriber database exposed by threat actor PHANTOM-SHADOW.', 'Netflix Demo 260M subscriber records leaked. Data includes emails, hashed passwords, payment card last 4 digits, plan type, profile count. PHANTOM-SHADOW group. Demo dataset. Streaming infrastructure credentials also found in stealer logs (kenji.watanabe@demo.invalid from netflix-demo.invalid CDN). PHANTOM-SHADOW uses PHANTOM-STEALER-01 for credential harvesting.', 'high', 86, 89, 'TLP:CLEAR', ARRAY['netflix','streaming','breach','260m','phantom-shadow','demo'], jsonb_build_array(jsonb_build_object('type','domain','value','netflix-demo.invalid'),jsonb_build_object('type','actor','value','PHANTOM-SHADOW')), jsonb_build_array(jsonb_build_object('type','domain','value','netflix-demo.invalid')), jsonb_build_array(jsonb_build_object('type','victim_of','value','PHANTOM-SHADOW')), '{}'::jsonb, true, 'synthetic'),

  -- Apple iCloud
  ('demo-evt-apple-001', NOW()-INTERVAL '42 days', 'breach', 'Demo Feed', 'synthetic', 'Apple Demo iCloud 900M accounts database for sale on darkweb', 'Apple Demo iCloud database with 900M accounts listed on AlphBay darkweb market.', 'Apple Demo iCloud database with 900M accounts for sale on AlphBay. Includes emails, phone numbers, hashed passwords, 2FA backup codes, iCloud storage tier. DEMO-RANSOM-02 linked. Apple Business Manager access also included (Brandon Scott enterprise admin creds from apple-demo.invalid MDM portal). PHANTOM-SHADOW linked via iCloud token grabber. Price: 0.05 BTC.', 'critical', 91, 87, 'TLP:CLEAR', ARRAY['apple','icloud','900m','darkweb','demo'], jsonb_build_array(jsonb_build_object('type','domain','value','apple-demo.invalid'),jsonb_build_object('type','actor','value','DEMO-RANSOM-02'),jsonb_build_object('type','actor','value','PHANTOM-SHADOW')), jsonb_build_array(jsonb_build_object('type','domain','value','apple-demo.invalid')), jsonb_build_array(jsonb_build_object('type','victim_of','value','DEMO-RANSOM-02')), '{}'::jsonb, true, 'synthetic'),

  -- PayPal
  ('demo-evt-paypal-001', NOW()-INTERVAL '38 days', 'breach', 'Demo Feed', 'synthetic', 'PayPal Demo 400M merchant accounts with balance data exposed', 'PayPal Demo merchant database with financial data exposed by CYBER-SHADOW.', 'PayPal Demo merchant accounts with verified balances for sale. Total accessible funds: $500K+ across affected merchants. Nina Patel (merchant.paypal@demo.invalid) balance $125K confirmed in stealer logs. business.paypal@demo.invalid API key exposed. CVE-2026-99999 (PayPal merchant API SQL injection) exploited. CYBER-SHADOW group. Darkweb price: 0.03 BTC.', 'critical', 92, 90, 'TLP:CLEAR', ARRAY['paypal','financial','merchant','breach','cyber-shadow','demo'], jsonb_build_array(jsonb_build_object('type','domain','value','paypal-demo.invalid'),jsonb_build_object('type','actor','value','CYBER-SHADOW'),jsonb_build_object('type','cve','value','CVE-2026-99999')), jsonb_build_array(jsonb_build_object('type','domain','value','paypal-demo.invalid')), jsonb_build_array(jsonb_build_object('type','victim_of','value','CYBER-SHADOW')), '{}'::jsonb, true, 'synthetic'),

  -- LinkedIn
  ('demo-evt-linkedin-001', NOW()-INTERVAL '41 days', 'breach', 'Demo Feed', 'synthetic', 'LinkedIn Demo 900M user profiles scraped by SILENT-RIFT', 'Professional network database scraped by SILENT-RIFT threat actor.', 'LinkedIn Demo 900M user profiles scraped over 6-month campaign by SILENT-RIFT group. Data includes names, job titles, company names, email addresses, connection counts, InMail credits. Andrew Wilson (recruiter.premium@demo.invalid) premium account credentials found in stealer logs. SILENT-RIFT uses SILENT-RIFT-SCRAPER-01 for automated data extraction. Demo dataset.', 'high', 87, 92, 'TLP:CLEAR', ARRAY['linkedin','professional','scraping','900m','silent-rift','demo'], jsonb_build_array(jsonb_build_object('type','domain','value','linkedin-demo.invalid'),jsonb_build_object('type','actor','value','SILENT-RIFT')), jsonb_build_array(jsonb_build_object('type','domain','value','linkedin-demo.invalid')), jsonb_build_array(jsonb_build_object('type','victim_of','value','SILENT-RIFT')), '{}'::jsonb, true, 'synthetic'),

  -- Steam / CYBER-SHADOW
  ('demo-evt-steam-001', NOW()-INTERVAL '60 days', 'breach', 'Demo Feed', 'synthetic', 'Steam Demo 15M gaming accounts with inventory data for sale', 'Gaming platform accounts with high-value inventory targeted by CYBER-SHADOW.', 'Steam Demo 15M gaming accounts with inventory data for sale on darkweb. Erik Johansson (gamer.pro@demo.invalid, steam_id=76561198012345678, wallet=$2,500) credentials captured by Aurora stealer. Developer.steam@demo.invalid API keys from Steamworks exposed. CYBER-SHADOW group selling at $50/account. Average inventory $500+ per account. VAC banned accounts included. Demo dataset.', 'medium', 75, 86, 'TLP:CLEAR', ARRAY['steam','gaming','inventory','cyber-shadow','demo'], jsonb_build_array(jsonb_build_object('type','domain','value','steam-demo.invalid'),jsonb_build_object('type','actor','value','CYBER-SHADOW')), jsonb_build_array(jsonb_build_object('type','domain','value','steam-demo.invalid')), jsonb_build_array(jsonb_build_object('type','victim_of','value','CYBER-SHADOW')), '{}'::jsonb, true, 'synthetic'),

  -- Sigma rules
  ('demo-evt-sigma-001', NOW()-INTERVAL '45 days', 'detection', 'Demo Feed', 'synthetic', 'Sigma rule: MetaCorp Fileshare Pro RCE - CVE-2026-99001 detection', 'Detection rule for CVE-2026-99001 exploitation against MetaCorp Fileshare Pro.', 'Sigma rule (sigma-meta-001): Detects exploitation attempts against MetaCorp Fileshare Pro upload endpoint. Looks for POST requests to /api/upload with large file uploads followed by .php file access. Status: stable. Level: critical. Logsource: webserver. Technique: T1190 (Exploitation for Initial Access). Tags: meta, fileshare, CVE-2026-99001. MITRE: T1190.', 'high', 82, 90, 'TLP:CLEAR', ARRAY['sigma','detection-rule','cve-2026-99001','meta','demo'], jsonb_build_array(jsonb_build_object('type','cve','value','CVE-2026-99001'),jsonb_build_object('type','domain','value','meta-corp.invalid')), jsonb_build_array(jsonb_build_object('type','cve','value','CVE-2026-99001')), jsonb_build_array(jsonb_build_object('type','detects','value','CVE-2026-99001')), '{}'::jsonb, true, 'synthetic'),

  -- Telegram channels
  ('demo-evt-telegram-001', NOW()-INTERVAL '45 days', 'forum_post', 'Demo Feed', 'synthetic', 'Telegram DarkLeaks channel distributes MetaCorp employee database', 'Dark web Telegram channel with 4500 members posting credential dumps.', 'Telegram channel DarkLeaks Underground (4500 members): Daily dumps of credential databases. Current: MetaCorp 500K employee database. admin.meta@demo.invalid:MetaBusiness@789 | MetaCorp Business Manager | admin=true. dark-operator-x admin confirmed. Channels linked: @DarkLeaks (4500 members), @ShadowBroker (stealer logs, 8000 members). Demo data only.', 'high', 80, 88, 'TLP:CLEAR', ARRAY['telegram','darkleaks','credential-dump','meta','demo'], jsonb_build_array(jsonb_build_object('type','domain','value','meta-corp.invalid'),jsonb_build_object('type','actor','value','@DarkOperatorX')), jsonb_build_array(jsonb_build_object('type','domain','value','meta-corp.invalid')), jsonb_build_array(jsonb_build_object('type','source','value','telegram-@DarkLeaks')), '{"channel_members":4500}'::jsonb, true, 'masked'),

  -- Correlation entries
  ('demo-evt-correl-001', NOW()-INTERVAL '44 days', 'correlation', 'Demo Feed', 'synthetic', 'Full attack chain correlation: MetaCorp breach by DEMO-APT-01 via CVE-2026-99001 and Raccoon stealer', 'Complete attack chain from initial access to data exfiltration mapped across multiple sources.', 'ATTACK CHAIN ANALYSIS: MetaCorp breach by DEMO-APT-01: PHASE 1 - Recon: Threat actor scans for MetaCorp Fileshare Pro (CVE-2026-99001). PHASE 2 - Initial Access: CVE-2026-99001 exploited, webshell DEMO-WEBSHELL-01 uploaded at /uploads/shell.php. C2: 198.51.100.50. PHASE 3 - Discovery: Stealer malware (Raccoon) deployed via phishing email to admin.meta@demo.invalid. PHASE 4 - Collection: Raccoon captures 234 credentials from meta-host-001 including VPN, FileShare, and cloud creds. PHASE 5 - Lateral Movement: Domain admin access via it.admin credentials. PHASE 6 - Exfiltration: 2.9B records exfiltrated over 48h. PHASE 7 - Extortion: Data posted on darkweb, DEMO-RANSOM-01 leak site. CORRELATED IOCs: meta-corp.invalid, 198.51.100.50, deadbeef..., admin.meta@demo.invalid, CVE-2026-99001.', 'critical', 97, 96, 'TLP:CLEAR', ARRAY['correlation','attack-chain','meta','demo-apt-01','cve-2026-99001','raccoon','full-analysis','demo'], jsonb_build_array(jsonb_build_object('type','actor','value','DEMO-APT-01'),jsonb_build_object('type','domain','value','meta-corp.invalid'),jsonb_build_object('type','cve','value','CVE-2026-99001'),jsonb_build_object('type','ip','value','198.51.100.50'),jsonb_build_object('type','malware','value','Raccoon'),jsonb_build_object('type','malware','value','DEMO-WEBSHELL-01'),jsonb_build_object('type','actor','value','DEMO-RANSOM-01')), jsonb_build_array(jsonb_build_object('type','domain','value','meta-corp.invalid'),jsonb_build_object('type','ip','value','198.51.100.50')), jsonb_build_array(jsonb_build_object('type','attack_chain_for','value','meta-corp.invalid')), '{}'::jsonb, true, 'synthetic'),

  ('demo-evt-correl-002', NOW()-INTERVAL '35 days', 'correlation', 'Demo Feed', 'synthetic', 'Full attack chain correlation: JPMorgan Demo Bank breach by ALPHV/BlackCat', 'Complete attack chain for JPMorgan Demo Bank financial sector breach.', 'ATTACK CHAIN ANALYSIS: JPMorgan Demo Bank breach by ALPHV/BlackCat: PHASE 1 - Initial Access: SQL injection (CVE-2026-99992) in trading platform order submission endpoint. PHASE 2 - Foothold: Vidar stealer deployed on jpm-host-002. PHASE 3 - Credential Harvest: 145 creds captured including Bloomberg Terminal (bloomberg.user@demo.invalid), trading system access. PHASE 4 - Privilege Escalation: Raccoon captures domain admin from jpm-host-003 (298 creds, it.operations@demo.invalid). PHASE 5 - Lateral Movement: Internal network access via Active Directory. PHASE 6 - Data Access: Bloomberg Terminal data, trading algorithms, risk dashboards accessed. PHASE 7 - Extortion: ALPHV auction on darkweb, starting $75K. C2: 203.0.113.200. CORRELATED IOCs: jpmorgan-demo.invalid, 203.0.113.200, CVE-2026-99992, Vidar stealer.', 'critical', 96, 94, 'TLP:CLEAR', ARRAY['correlation','attack-chain','jpmorgan','alphv','cve-2026-99992','vidar','full-analysis','demo'], jsonb_build_array(jsonb_build_object('type','actor','value','ALPHV/BlackCat'),jsonb_build_object('type','domain','value','jpmorgan-demo.invalid'),jsonb_build_object('type','cve','value','CVE-2026-99992'),jsonb_build_object('type','ip','value','203.0.113.200'),jsonb_build_object('type','malware','value','Vidar'),jsonb_build_object('type','malware','value','Raccoon')), jsonb_build_array(jsonb_build_object('type','domain','value','jpmorgan-demo.invalid'),jsonb_build_object('type','ip','value','203.0.113.200')), jsonb_build_array(jsonb_build_object('type','attack_chain_for','value','jpmorgan-demo.invalid')), '{}'::jsonb, true, 'synthetic');

COMMIT;
